hollow/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('website.urls'), name="index"),
    path('admin/', admin.site.urls),
]

website/urls.py
from django.conf.urls import url
from django.urls import path
from django.contrib.auth import views as auth_views

from website import views

urlpatterns = [
    path('', views.IndexView.index, name='index'),
    path('usuário/', views.UserView.user, name='user_profile'),
    path('usuário/mudar-informações', views.ChangeUserInformationView.edit_profile, name='change_information'),
    path('usuário/mudar-senha', views.ChangePasswordView.changed_password, name='change_password'),
    path('usuário/<int:user_id>', views.UserView.user_profile),
    path('login/', views.LoginView.login, name='login'),
    path('logout/', views.LogoutView.logout, name='logout'),
    path('cadastro/', views.RegisterView.register_user, name='register'),
    path('cadastro/aluno/', views.RegisterView.register_user, name='form_user'),
    path('indique-e-ganhe/', views.ReferAndWinView.as_view, name='referandwin'),
    path('como-funciona', views.HowItWorksView.as_view, name='howitworks'),
    path('quem-somos', views.WhoWeAreView.as_view, name='whoweare'),
    path('contato', views.ContactView.as_view, name='contact'),
    path('trabalhe-conosco', views.WorkWithUsView.as_view, name='workwithus'),
    path('cursos', views.CoursesView.courses_view, name='all_courses'),
    path('cursos/<int:course_id>/', views.CoursesView.as_view, name='courses'),

    # Forget Password
    path('password-rewset/',
         auth_views.PasswordResetView.as_view(
             template_name='website/commons/password-reset/password_reset.html',
             subject_template_name='website/commons/password-reset/password_reset_subject.txt',
             email_template_name='website/commons/password-reset/password_reset_email.html',
             success_url='/password-reset/done/'
         ),
         name='password_reset'),
    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(
             template_name='website/commons/password-reset/password_reset_done.html'
         ),
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(
             template_name='website/commons/password-reset/password_reset_confirm.html'
         ),
         name='password_reset_confirm'),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='website/commons/password-reset/password_reset_complete.html'
         ),
         name='password_reset_complete'),
]

website/models/user.py
from django.contrib.auth.base_user import AbstractBaseUser
from django.db import models
from phonenumber_field.modelfields import PhoneNumberField

from website.managers import CustomUserManager


def upload_to_name(instance, filename):
    # TODO: Change to 'static/website/profile_pictures/' in production !!!
    return 'website/static/website/profile_pictures/' + filename


class User(AbstractBaseUser):
    """"
    The most important model of our app
    It models the user class

    Interactions with the platform
        - The registration
        - Validation by Admin
        - Add/Change data
        - Personal events (later)
        - Personal development (later)


    Tests that are mandatory
        - The registration was well done
        - Make a check on the registration parameters
        - All required fiels are filled in


    """

    # CHOICES
    GENDER_CHOICES = (
        ('M', 'Masculino'),
        ('F', 'Feminino'),
        ('O', 'Outro / Não quero declarar')
    )

    # DATABASE FIELDS
    first_name = models.CharField(max_length=300, blank=True, null=True)
    last_name = models.CharField(max_length=500)
    email = models.EmailField(unique=True)
    telephone = PhoneNumberField(blank=True, null=True)
    birthday = models.DateField('Data de nascimento', blank=True, null=True)
    gender = models.CharField(max_length=1, choices=GENDER_CHOICES)
    photo = models.FileField(upload_to=upload_to_name,
                             blank=True)
    job_title = models.CharField(max_length=100, blank=True, null=True)
    twitter_link = models.CharField(max_length=200, blank=True, null=True)
    facebook_link = models.CharField(max_length=200, blank=True, null=True)
    linkedin_link = models.CharField(max_length=200, blank=True, null=True)
    is_subscribed_newsletter = models.BooleanField(default=False)
    address = models.CharField(max_length=500, blank=True, null=True)
    address_complement = models.CharField(max_length=500, blank=True, null=True)
    zip_code = models.IntegerField(blank=True, null=True)
    city = models.CharField(max_length=100, blank=True, null=True)
    country = models.CharField(max_length=100, blank=True, null=True)

    # Required fields to extend AbstractBaseUser
    date_joined = models.DateTimeField(verbose_name='date joined', auto_now_add=True)
    last_login = models.DateTimeField(verbose_name='last login', auto_now=True)
    is_admin = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    is_superuser = models.BooleanField(default=False)

    objects = CustomUserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    # MANAGERS

    # META CLASS
    class Meta:
        verbose_name = 'Usuário'
        verbose_name_plural = 'Usuários'

    # TO STRING METHOD
    def __str__(self):
        return "%s %s" % (self.first_name, self.last_name)

    # SAVE METHOD

    # ABSOLUTE URL METHOD

    # OTHER METHODS
    def has_perm(self, perm, obj=None):
        return self.is_admin

    def has_module_perms(self, app_label):
        return True

    def get_full_name(self):
        """
        Returns the first_name plus the last_name, with a space in between.
        """
        full_name = '%s %s' % (self.first_name, self.last_name)
        return full_name.strip()

    def get_short_name(self):
        """
        Returns the short name for the user.
        """
        return self.first_name

    def email_user(self, subject, message, from_email=None, **kwargs):
        """
        Sends an email to this User.
        Not working for now
        """
        # send_mail(subject, message, from_email, [self.email], **kwargs)

website/forms/change_user_information.py
from django import forms
from django.forms import DateInput
from phonenumber_field.formfields import PhoneNumberField

from website.models import User


class EditProfileForm(forms.ModelForm):
    telephone = PhoneNumberField(label="Número de telefone : ", required=False)
    twitter_link = forms.CharField(label='Link twitter : ', required=False)
    linkedin_link = forms.CharField(label='Link LinkedIn : ', required=False)
    first_name = forms.CharField(label='Primeiro nome : ', required=True)

    class Meta:
        model = User
        fields = (
            'first_name',
            'last_name',
            'telephone',
            'gender',
            'photo',
            'birthday',
            'job_title',
            'twitter_link',
            'linkedin_link',
            'is_subscribed_newsletter',
            'address',
            'address_complement',
            'zip_code',
            'city',
            'country'
        )
        labels = {
            'last_name': 'Nome de família : ',
            'birthday': 'Data de nascimento : ',
            'job_title': 'Profissão : ',
            'gender': 'Sexo : ',
            'photo': 'Foto de perfil',
            'is_subscribed_newsletter': 'Gostaria de me inscrever na newsletter',
            'address': 'Endereço : ',
            'address_complement': 'Complemento do endereço : ',
            'zip_code': 'Código postal : ',
            'city': 'Cidade : ',
        }
        widgets = {
            'birthday': DateInput(),
        }

website/forms/user_registration.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from phonenumber_field.formfields import PhoneNumberField

from website.models import User


class DateInput(forms.DateInput):
    input_type = 'date'


class UserRegistrationForm(UserCreationForm):
    telephone = PhoneNumberField(label="Número de telefone : ", required=False)
    twitter_link = forms.CharField(label='Link twitter : ', required=False)
    linkedin_link = forms.CharField(label='Link LinkedIn : ', required=False)
    first_name = forms.CharField(label='Primeiro nome : ', required=True)

    class Meta:
        model = User
        fields = (
            'first_name',
            'last_name',
            'email',
            'password1',
            'password2',
            'telephone',
            'gender',
            'photo',
            'birthday',
            'job_title',
            'twitter_link',
            'linkedin_link',
            'is_subscribed_newsletter',
            'address',
            'address_complement',
            'zip_code',
            'city',
            'country'
        )
        labels = {
            'email': 'Email : ',
            'last_name': 'Nome de família : ',
            'birthday': 'Data de nascimento : ',
            'job_title': 'Profissão : ',
            'gender': 'Sexo : ',
            'photo': 'Foto de perfil',
            'is_subscribed_newsletter': 'Gostaria de me inscrever na newsletter',
            'address': 'Endereço : ',
            'address_complement': 'Complemento do endereço : ',
            'zip_code': 'Código postal : ',
            'city': 'Cidade : ',
        }
        widgets = {
            'birthday': DateInput(),
        }

website/views/courses.py
from django.shortcuts import render
from django.views import generic

from website.models import Course


class CoursesView(generic.ListView):
    def as_view(request, course_id):
        course = Course.objects.get(id=course_id)
        context = {
            "course": course
        }
        return render(request, 'website/course_page.html', context)

    def courses_view(request):

        courses = Course.objects.all()

        return render(request, 'website/courses.html', {'courses': courses})

website/views/hollow.py
from django.shortcuts import render
from django.views import generic


class ReferAndWinView(generic.ListView):
    def as_view(request):
        return render(request, 'website/referandwin.html')


class HowItWorksView(generic.ListView):
    def as_view(request):
        return render(request, 'website/howitworks.html')


class WhoWeAreView(generic.ListView):
    def as_view(request):
        return render(request, 'website/whoweare.html')


class ContactView(generic.ListView):
    def as_view(request):
        return render(request, 'website/contact.html')


class WorkWithUsView(generic.ListView):
    def as_view(request):
        return render(request, 'website/workwithus.html')

website/views/index.py
from django.shortcuts import render
from django.views import generic


class IndexView(generic.ListView):
    template_name = 'website/index.html'

    def index(request):
        """"
        Temporary solution while we do not construct the queryset method
        """

        return render(request, 'website/index.html')

website/views/login.py
from django.contrib.auth import login, authenticate, logout
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect
from django.views import generic

from website.forms import UserRegistrationForm
from website.models import User


def error(request, message="Ooops! Aconteceu um erro, vamos investigar, desculpe por esse problema!"):
    # This special view is called everytime there is an error to display it into the browser
    return render(request, 'website/error.html', {'messages': request.messages, })


class RegisterView:
    def register(request):
        return render(request, 'website/register.html')

    def register_user(request):
        context = {}
        if request.POST:
            form = UserRegistrationForm(request.POST, request.FILES or None)
            if form.is_valid():
                incomplete_user = form.save(commit=False)
                incomplete_user.is_active = True
                email = form.cleaned_data.get('email')
                raw_password = form.cleaned_data.get('password1')
                incomplete_user.save()
                login(request, incomplete_user, backend='django.contrib.auth.backends.ModelBackend')
                return redirect('login')
            else:
                context['user_registration_form'] = form
        else:
            user_form = UserRegistrationForm()
            context['user_registration_form'] = user_form
        return render(request, 'website/register_user.html', context)


class LoginView(generic.ListView):
    def login(request):
        if request.method == 'POST':
            email = request.POST['email']
            password = request.POST['password']
            queryset = User.objects.filter(email=email)
            if len(queryset) != 0:
                if queryset[0].is_active:
                    user = authenticate(email=email, password=password)
                    if user is not None:
                        login(request, user)
                        return redirect('index')
                    else:
                        request.messages.append({
                            "type": "warning",
                            "header": "Erro causado pela senha incorreta",
                            "content": "Senha incorreta"
                        })
                        return error(request)
                else:
                    print('inactive')
                    request.messages.append({
                        "type": "warning",
                        "header": "Erro ligado a sua conta",
                        "content": "Sua conta ainda não foi ativada ou foi deletada"
                    })
                    return error(request)

            else:
                request.messages.append({
                    "type": "warning",
                    "header": "Erro ligado ao email",
                    "content": "Email incorreto"
                })
                return error(request)
        else:
            return render(request, 'website/login.html')


class LogoutView(generic.ListView):
    def logout(request):
        logout(request)
        return HttpResponseRedirect('/')

website/views/user.py
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib import messages
from django.shortcuts import render, redirect
from django.views import generic

from website.forms.change_user_information import EditProfileForm
from website.models import User


class UserView(generic.ListView):
    template_name = 'website/user_profile.html'

    def user(request):
        """"
        Temporary solution while we do not construct the queryset method
        """

        return render(request, 'website/user_profile.html')

    def user_profile(request, user_id):
        """"
        Temporary solution while we do not construct the queryset method
        """

        try:
            user = User.objects.get(id=user_id)
            return render(request, 'website/user_profile.html', {'user': user})
        except User.DoesNotExist:
            return render(request, 'website/user_does_not_exist.html')



class ChangePasswordView(generic.ListView):
    template_name = 'website/change_password.html'

    def changed_password(request):
        if request.method == 'POST':
            form = PasswordChangeForm(request.user, request.POST)
            if form.is_valid():
                user = form.save()
                update_session_auth_hash(request, user)  # Important!
                messages.success(request, 'Your password was successfully updated!')
                return redirect('change_password')
            else:
                messages.error(request, 'Please correct the error below.')
        else:
            form = PasswordChangeForm(request.user)
        return render(request, 'website/change_password.html', {
            'form': form
        })


class ChangeUserInformationView:
    template_name = 'website/change_information.html'

    def edit_profile(request):
        form = EditProfileForm(request.POST or None, instance=request.user)

        if form.is_valid():
            form.save()
            return redirect('user_profile')

        else:
            form = EditProfileForm(request.POST or None, instance=request.user)
            context = {'form': form}
            return render(request, 'website/change_information.html', context)

website/templates/website/change_information.html
{% extends 'website/layout/base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}Hollow - Mudar informações{% endblock title %}
{% block content %}
    <h1 style="color:yellow">Mudar minhas informações</h1>

    <div class="container">
        <form method="post">
            {% csrf_token %}
            {{ form|crispy  }}
            <button type="submit">Mudar informações</button>
        </form>
    </div>





{% endblock content %}

website/templates/website/change_password.html
{% extends 'website/layout/base.html' %}
{% load static %}

{% block title %}Hollow - Mudar senha{% endblock title %}
{% block content %}
    <h1 style="color:yellow">Mudar minha senha</h1>



    <form method="post">
        {% csrf_token %}
        {{ form }}
        <button type="submit">Save changes</button>
    </form>



{% endblock content %}

website/templates/website/course_page.html
{% extends 'website/layout/base.html' %}
{% load static %}

{% block title %}Hollow - Area de Cursos{% endblock title %}

{% block content %}
    <link rel="stylesheet" type="text/css" href="{% static 'website/css/course.css' %}">
    <div class="row justify-content-center">
        <div class="row col-md-12 align-items-center justify-content-center" id="title-header">
            <h1 class="align-self-center hollow-font">{{ course.title }}</h1>
        </div>
    </div>
    </br>
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="list-group">
                {% for macrotopic in course.macrotopic.all %}
                <div class="list-group-item without-side-border">
                    <div class="row col-md-12 align-content-center" style="height: 5vh">
                        <button class="btn btn-link-hollow"
                                data-toggle="collapse"
                                data-target="#collapse{{ macrotopic.id }}"
                                aria-expanded="false"
                                aria-controls="collapse{{ macrotopic.id }}">
                            <span class="col-md-2">{{ forloop.counter }}</span>
                            <span class="col-md-8">{{ macrotopic.title }}</span>
                        </button>
                    </div>
                    <div class="col-md-12">
                        <div class="list-group collapse" id="collapse{{ macrotopic.id }}">
                            {% for microtopic in macrotopic.microtopic.all %}
                                <div class="list-group-item without-side-border">
                                    <div class="row justify-content-center">
                                        <div class="row col-md-12 align-content-center" style="height: 5vh">
                                            <span class="row col-md-10 align-content-center">
                                                <button class="btn btn-link-hollow"
                                                        data-toggle="collapse"
                                                        data-target="#collapse{{ microtopic.id }}-micro"
                                                        aria-expanded="true"
                                                        aria-controls="collapse{{ microtopic.id }}-micro">
                                                {{ microtopic.title }}
                                                </button>
                                            </span>
                                            <span class="row col align-content-center">
                                                {{ microtopic.video.duration }}
                                            </span>
                                            <span class="row col align-content-center">
                                                <svg width="1.5em" height="1.5em" viewBox="0 0 16 16" class="bi bi-check-circle-fill yellow-hollow" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                                                    <path fill-rule="evenodd"
                                                          d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-3.97-3.03a.75.75 0 0 0-1.08.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-.01-1.05z"/>
                                                </svg>
                                            </span>
                                        </div>
                                        <div class="col-md-10 justify-content-center collapse" id="collapse{{ microtopic.id }}-micro">
                                            <div class="embed-responsive embed-responsive-16by9 py-0 my-0">
                                                <iframe class="embed-responsive-item" src="{{ microtopic.video.url }}"
                                                allowfullscreen></iframe>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            {% endfor %}
                        <div class="list-group-item without-side-border without-bottom-border">
                            <div class="row col-md-12 align-content-center" style="height: 5vh">
                            {{ macrotopic.exercise_list }}
                            </div>
                        </div>
                        </div>

                    </div>

                </div>
                {% endfor %}
            </div>
        </div>
    </div>

{% endblock content %}

website/templates/website/courses.html
{% extends 'website/layout/base.html' %}
{% load static %}

{% block title %}Hollow - Cursos{% endblock title %}

{% block content %}

    {% for course in courses %}
        <div class="blog-card">

            <div class="description text-left">
                <h1>{{ course.title }}</h1>
                <h2>{{ course.begin_date|date:"j F o à G:i" }}</h2>
                <p class="read-more">
                    <a href="/cursos/{{ course.id }}">Ver mais</a>
                </p>
            </div>
        </div>

    {% endfor %}


{% endblock content %}

website/templates/website/error.html
{% extends 'website/layout/base.html' %}
{% load static %}

{% block title %}Oops, erro aqui!{% endblock title %}

{% block mystylesheet %}
    <link rel="stylesheet" type="text/css" href="{% static 'website/css/error.css' %}">
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
{% endblock mystylesheet %}

{% block content %}
    <div class="ui {{ message.type }} floating message container">
        {% for message in messages %}
            <h3>Error</h3>
            <hr class="light my-4"/>
            <div class="header">
                {{ message.header }}
            </div>
            <p>{{ message.content }}</p>
        {% endfor %}
    </div>
{% endblock content %}

website/templates/website/howitworks.html
{% extends 'website/layout/base.html' %}
{% load static %}

{% block title %}Hollow - Como funciona{% endblock title %}

{% block content %}

    <div class="d-flex align-items-center image-header">
        <img class="image-1 img-fluid" src="{% static 'website/img/big_image_01.png' %}">
        <img class="image-page-title" src="{% static 'website/img/how_it_works_title.png' %}">
    </div>
    <!--image-header-->

    <div class="container-fluid py-3" style=
            'background: url("{% static 'website/img/how_it_works_bg.png' %}") scroll;
                    background-size:50%;'
    >
        <div class="row py-4">
            <div class="col-12 text-center">
                <h2 class="yellow-hollow font-weight-bold text-capitalize">POTENCIALIZE SEU DESEMPENHO</h2>
                <div class="container text-center col-8">
                    <h3 class="text-muted text-center">Após assinar um dos nossos planos, terá acesso completo e
                        ilimitado a todos os seguintes recursos:</h3>
                </div>
            </div>
        </div>
        <!--text-1-->
        <div class="row py-4 px-5">
            <div class="col-md-6 col-sm-12 py-2 text-right align-self-center">
                <h2 class="yellow-hollow font-weight-bold text-capitalize">VIDEO AULAS</h2>
                <h3 class="text-muted text-right">Serão curtas, específicas e precisas.</h3>
                <div class="py-2">
                    <img class="img-icon img-fluid" src="{% static 'website/img/pc_yellow.png' %}">
                </div>
            </div>
            <div class="col-md-6 col-sm-12 py-2 ">
                <img class="img-fluid shadow-lg align-self-center"
                     src="{% static 'website/img/girl_video_classes.png' %}">
            </div>
        </div>
        <!--text-on-left-->
        <div class="row py-4 px-5">
            <div class="col-md-6 col-sm-12 py-2 align-self-center">
                <img class="img-fluid shadow-lg align-self-center" src="{% static 'website/img/group_pre_test.png' %}">
            </div>
            <div class="col-md-6 col-sm-12 py-2 text-right align-self-center">
                <h2 class="yellow-hollow font-weight-bold text-capitalize">FÓRUM EM DIRETO PRÉ PROVA</h2>
                <h3 class="text-muted text-left">Com o apoio dos nossos instrutores, as suas dúvidas ficarão no
                    passado.</h3>
                <div class="py-2">
                    <img class="img-icon" src="{% static 'website/img/doubt_yellow.png' %}">
                </div>
            </div>
        </div>

        <!--text-on-right-->
        <div class="row py-4 px-5">
            <div class="col-md-6 col-sm-12 py-2 text-right align-self-center">
                <h2 class="yellow-hollow font-weight-bold text-capitalize">PROVAS E EXERCÍCIOS RESOLVIDOS</h2>
                <h3 class="text-muted text-right">Depois da teoria está na hora de colocar em prática. Para isso, temos
                    diversos exercícios e provas resolvidas passo a passo.</h3>
                <div class="py-2">
                    <img class="img-icon" src="{% static 'website/img/test_yellow.png' %}">
                </div>
            </div>
            <div class="col-md-6 col-sm-12 py-2 align-self-center ">
                <img class="img-fluid shadow-lg" src="{% static 'website/img/books_and_ipad.png' %}">
            </div>
        </div>
        <!--text-on-left-->
    </div>
    <!--page-content-->

{% endblock content %}

website/templates/website/index.html
{% extends 'website/layout/base.html' %}
{% load static %}


{% block title %}
Hollow - Homepage
{% endblock title %}

{% block content %}

<!--image and start now buttons-->
<section>
    <div class="row index-main-image">
        <img src="{% static 'website/img/index/index_header_bg.png' %}" class="col-12">
        <img src="{% static 'website/img/index/transforme_text.png' %}" class="col-10 index-text-over-image">
        <div class="btn-group-vertical index-start-now-buttons">
            <button class="btn btn-warning index-start-button"><a href="" class="index-start-link">Comece
                    agora!</a></button>
            <button class="btn btn-link"><a href="" class="index-start-link">Saiba mais</a></button>
        </div>
    </div>
</section>

<!--video section-->
<section>
    <div class="row index-video">
        <div class="col-12">
            <iframe src="https://www.youtube.com/embed/tgbNymZ7vqY" frameborder="0"
                allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture"
                allowfullscreen></iframe>
        </div>
        <div>
</section>

<!--Animated boxes section-->
<section>
    <div class="row justify-content-around">
        <div class="col-small">
            <!--This img's tags has id's for javacript usage-->
            <img src="{% static 'website/img/index/indextextbox1.png' %}" class="index-text-box" id="index-text-box1">
        </div>
        <div class="col-small">
            <img src="{% static 'website/img/index/indextextbox2.png' %}" class="index-text-box" id="index-text-box2">
        </div>
        <div class="col-small">
            <img src="{% static 'website/img/index/indextextbox3.png' %}" class="index-text-box" id="index-text-box3">
        </div>

</section>

<script>
    var textBox1 = document.getElementById("index-text-box1");
    textBox1.addEventListener("mouseover", () => {
        if (
            textBox1.src.match("{% static 'website/img/index/index_header_bg.png' %}")
        ) {
            textBox1.src = "{% static 'website/img/index/indextextbox1.png' %}";
        } else {

            textBox1.src = "{% static 'website/img/index/index_header_bg.png' %}";
        }
    });
</script>



{% endblock %}

website/templates/website/register.html
{% extends 'website/layout/base.html' %}
{% load static %}

{% block title %}Hollow - entre para o time{% endblock title %}

{% block content %}

    <div class="container py-2">
        <a href="{% url 'form_user' %}">
            <button class="btn-warning-hollow" type="button">
                Estudante
            </button>
        </a>
    </div>
{#    TODO: See how we are going to deal with this file#}


{% endblock content %}

{% block myjssheet %}
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script>
        $(function () {
            $("#id_birthday").datepicker();
        });
    </script>
{% endblock myjssheet %}

website/templates/website/user_profile.html
{% extends 'website/layout/base.html' %}
{% load static %}

{% block title %}Hollow - {{ user.first_name }}{% endblock title %}

{% block content %}
    <h1 style="color:yellow">{{ user.first_name }} {{ user.last_name }}</h1>






{% endblock content %}